name: CI workflow

on:
  push:
    branches:
      - "main"
  
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # Run flake8 with error checks
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          # Run flake8 with complexity and line length checks
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: notests
        run: |
          # Run unit tests with coverage
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app